/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import newq.menu;

/**
 *
 * @author casa
 */
public class calculadora extends javax.swing.JFrame {

    /**
     * Creates new form calculadora
     */
    
    private int a;

    public void setA(int a) {
        this.a = a;
    }
    
    public int getA() {
        return a;
    }
    
    
    
    public calculadora() {
        setA(0);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioOp = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        n1Txt = new javax.swing.JTextField();
        n2Txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        sumaR = new javax.swing.JRadioButton();
        restaR = new javax.swing.JRadioButton();
        multiR = new javax.swing.JRadioButton();
        divisionR = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        calcBtn = new javax.swing.JButton();
        eraBtn = new javax.swing.JButton();
        exiBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        rLbl = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Calculadora");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 40));
        getContentPane().add(n1Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 200, 34));
        getContentPane().add(n2Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 200, 34));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Numero 1");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 130, 34));

        radioOp.add(sumaR);
        sumaR.setText("Suma");
        sumaR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumaRActionPerformed(evt);
            }
        });
        getContentPane().add(sumaR, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        radioOp.add(restaR);
        restaR.setText("Resta");
        restaR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaRActionPerformed(evt);
            }
        });
        getContentPane().add(restaR, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, -1));

        radioOp.add(multiR);
        multiR.setText("Multiplicacion");
        multiR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiRActionPerformed(evt);
            }
        });
        getContentPane().add(multiR, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        radioOp.add(divisionR);
        divisionR.setText("Division");
        divisionR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionRActionPerformed(evt);
            }
        });
        getContentPane().add(divisionR, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Numero 2");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 130, 34));

        calcBtn.setText("Calcular");
        calcBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcBtnActionPerformed(evt);
            }
        });
        getContentPane().add(calcBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 120, 30));

        eraBtn.setText("Borrar");
        eraBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eraBtnActionPerformed(evt);
            }
        });
        getContentPane().add(eraBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 120, 30));

        exiBtn.setText("Salir");
        exiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exiBtnActionPerformed(evt);
            }
        });
        getContentPane().add(exiBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 120, 30));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Resultado");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 100, 34));

        rLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(rLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 200, 34));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/sakurajima_mai.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void restaRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaRActionPerformed
        setA(2);
    }//GEN-LAST:event_restaRActionPerformed

    private void exiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exiBtnActionPerformed
        menu menu = new menu();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_exiBtnActionPerformed

    private void eraBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eraBtnActionPerformed
        this.n1Txt.setText("");
        this.n2Txt.setText("");
        this.rLbl.setText("");
        
        switch(getA()){
            case 1:
                this.sumaR.setSelected(false);
                break;
            case 2:
                this.restaR.setSelected(false);
                break;
            case 3:
                this.multiR.setSelected(false);
                break;
            case 4:
                this.divisionR.setSelected(false);
                break;
        }
    }//GEN-LAST:event_eraBtnActionPerformed

    private void sumaRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumaRActionPerformed
        setA(1);
    }//GEN-LAST:event_sumaRActionPerformed

    private void multiRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiRActionPerformed
        setA(3);
    }//GEN-LAST:event_multiRActionPerformed

    private void divisionRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionRActionPerformed
        setA(4);
    }//GEN-LAST:event_divisionRActionPerformed

    private void calcBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcBtnActionPerformed
        try {
            double n1 = Double.parseDouble(this.n1Txt.getText());
            double n2 = Double.parseDouble(this.n2Txt.getText());
            double op;

            if (this.n1Txt.getText() == null) {
                n1 = 0;
            } else if (this.n2Txt.getText() == null) {
                n2 = 0;
            } else if (this.n1Txt.getText() == null && this.n1Txt.getText() == null) {
                n1 = 0;
                n2 = 0;
            }

            switch (getA()) {
                case 1:
                    op = n1 + n2;
                    this.rLbl.setText(String.valueOf(op));
                    break;
                case 2:
                    op = n1 - n2;
                    this.rLbl.setText(String.valueOf(op));
                    break;
                case 3:
                    op = n1 * n2;
                    this.rLbl.setText(String.valueOf(op));
                    break;
                case 4:
                    if (n2 == 0) {
                        this.rLbl.setText("Math Error");
                    } else {
                        op = n1 / n2;
                        this.rLbl.setText(String.valueOf(op));
                    }
                    break;
                default:
                    op = 0;
                    break;
            }
        } catch (Exception e) {
            rLbl.setText(String.valueOf(0));
        }
    }//GEN-LAST:event_calcBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcBtn;
    private javax.swing.JRadioButton divisionR;
    private javax.swing.JButton eraBtn;
    private javax.swing.JButton exiBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton multiR;
    private javax.swing.JTextField n1Txt;
    private javax.swing.JTextField n2Txt;
    private javax.swing.JLabel rLbl;
    private javax.swing.ButtonGroup radioOp;
    private javax.swing.JRadioButton restaR;
    private javax.swing.JRadioButton sumaR;
    // End of variables declaration//GEN-END:variables
}
