/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import newq.menu;

/**
 *
 * @author casa
 */
public class estudiantes extends javax.swing.JFrame {

    /**
     * Creates new form estudiantes
     */
    public estudiantes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        n1Spin = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        n2Spin = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        r2Lbl = new javax.swing.JLabel();
        r1Lbl = new javax.swing.JLabel();
        calcBtn = new javax.swing.JButton();
        eraserBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        n2Txt = new javax.swing.JTextField();
        n1Txt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Estudiantes");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 557, 44));

        n1Spin.setModel(new javax.swing.SpinnerNumberModel(1, 0, 50, 1));
        n1Spin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                n1SpinStateChanged(evt);
            }
        });
        getContentPane().add(n1Spin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 20, 34));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 55, 200, 34));

        n2Spin.setModel(new javax.swing.SpinnerNumberModel(1, 0, 50, 1));
        n2Spin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                n2SpinStateChanged(evt);
            }
        });
        getContentPane().add(n2Spin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 20, 34));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("jLabel2");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 107, 200, 34));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Porcentage de hombres");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 159, 200, 34));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Porcentage de mujeres");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 211, 200, 34));

        r2Lbl.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(r2Lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 211, 200, 34));

        r1Lbl.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(r1Lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 159, 200, 34));

        calcBtn.setText("Calcular");
        calcBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcBtnActionPerformed(evt);
            }
        });
        getContentPane().add(calcBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 263, 130, 30));

        eraserBtn.setText("Borrar");
        eraserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eraserBtnActionPerformed(evt);
            }
        });
        getContentPane().add(eraserBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 263, 130, 30));

        exitBtn.setText("Salir");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 263, 130, 30));
        getContentPane().add(n2Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 200, 34));
        getContentPane().add(n1Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 200, 34));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/black-nawpic-15.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void n1SpinStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_n1SpinStateChanged
        this.n1Txt.setText(this.n1Spin.getValue().toString());
    }//GEN-LAST:event_n1SpinStateChanged

    private void n2SpinStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_n2SpinStateChanged
        this.n2Txt.setText(this.n2Spin.getValue().toString());
    }//GEN-LAST:event_n2SpinStateChanged

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        menu menu = new menu();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_exitBtnActionPerformed

    private void eraserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eraserBtnActionPerformed
        this.n1Txt.setText("");
        this.n2Txt.setText("");
        this.n1Spin.setValue(0);
        this.n2Spin.setValue(0);
        this.r1Lbl.setText("");
        this.r2Lbl.setText("");
        this.n1Txt.grabFocus();
    }//GEN-LAST:event_eraserBtnActionPerformed

    private void calcBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcBtnActionPerformed
        float nho = Float.parseFloat(this.n1Txt.getText());
        float nmu = Float.parseFloat(this.n2Txt.getText());
        
        float fe = nho + nmu;
        
        float pho = (nho * 100) / fe;
        float pmu = (nmu * 100) / fe;
        
        this.r1Lbl.setText("%"+String.valueOf(pho));
        this.r2Lbl.setText("%"+String.valueOf(pmu));
    }//GEN-LAST:event_calcBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(estudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(estudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(estudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(estudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new estudiantes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcBtn;
    private javax.swing.JButton eraserBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSpinner n1Spin;
    private javax.swing.JTextField n1Txt;
    private javax.swing.JSpinner n2Spin;
    private javax.swing.JTextField n2Txt;
    private javax.swing.JLabel r1Lbl;
    private javax.swing.JLabel r2Lbl;
    // End of variables declaration//GEN-END:variables
}
